services:
  db:
    image: postgres:16
    container_name: postgres-tour
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: tourist_club_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      # - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/posgresql/data

    ports:
      -"5432:5432"
volumes:
  posgres_data:
